### ISSUE TITLE
Want to implement mouse click events for navigating instead of number writing

### ISSUE THREAD

**Issue by jayskhatri** [jayskhatri/Super-Market-Management#1]

**Comment by jayskhatri** [comment]
It would be great if you can help me.

**Comment by werewolf-spirit** [comment]
Hi! What exactly do you need?

**Comment by Manvi07** [comment]
Hi @jayskhatri please provide some description

**Comment by Abubakar548** [comment]
where exactly is number writing operation?

**Comment by AbhiShingane** [comment]
@jayskhatri 
Please provide the exact requirement and plan for this project.

**Comment by Gravity-I-Pull-You-Down** [comment]
Hi, @jayskhatri  can you please provide some more details about the feature you are willing to implement, that is if this issue is open.
